### ISSUE TITLE
Attempting to break hardlink on Linux fails (writes to `/` directory?)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/gawk-feedstock#1]
Recently we tightened down the permissions in the Linux Docker container and started running as a non-`root` user (named `conda`). It seems that `gawk` creates a hardlink that `conda-build` tries to break. However the way `conda-build` tries to break it involves writing to a file it creates, `tmpfile`, in the `/` directory. Of course, this would not be permitted for a non-`root` user. Not sure why it tries to write to that location in the Linux Docker container. The same issue does not seem to be occurring on macOS.

```python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 133, in _copy_with_shell_fallback
    stderr=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cp -a /feedstock_root/build_artefacts/gawk_1515267789327/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/gawk-4.2.0 /tmpfile' returned non-zero exit status 1.
```

ref: https://circleci.com/gh/conda-forge/gawk-feedstock/1

**Comment by jakirkham** [comment]
Do you have any hints as to why this might be happening @msarahan?

**Comment by bollwyvl** [comment]
Hooray for non-root docker. I'll look into the makefile... The location of
the tmpdir is likely configurable...

**Comment by jakirkham** [comment]
Yeah, was going to try testing out a theory about what is happening.

**Comment by jakirkham** [comment]
Hmm...thought it might be environment variable related, but that does not seem to be the case. Also thought it might be related to where these directories are being mounted, but that doesn't seem to be the case either.

As a workaround, have put PR ( https://github.com/conda-forge/gawk-feedstock/pull/2 ) together, which pulls from the `root`-based `condaforge/linux-anvil` image. This is a temporary workaround and I have no clue when that image might expire, but it may be sufficient for publishing the packages that you need near term.

**Comment by bollwyvl** [comment]
Thanks, merge looks good, haven't tested it yet (afk) but my local builds have been working.

I just switched back locally to Linux (fedora) and hadn't encountered this issue in all my (non-root) testing... But will try the ci docker build scripts.

Thanks again for pushing this though!

**Comment by jakirkham** [comment]
I think I figured it out. The issue is that we run `conda-build` from `/` and that it is where it is writing the file. If we switch to `/home/conda`, this issue goes away. Already have a PR open on the docker image to fix this. Will rebuild it and we can take the new image for a spin.

**Comment by jakirkham** [comment]
Alright looks like we fixed it in PR ( https://github.com/conda-forge/gawk-feedstock/pull/3 ). Thanks for your patience and help working on this issue, @bollwyvl.
